package dev.loomstudios.client.screen;
import dev.loomstudios.client.ui.*;
import dev.loomstudios.client.project.*;
import dev.loomstudios.project.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.KeyEvent;
import net.minecraft.network.chat.Component;
import java.util.*;
public final class LoomLayerManagerScreen extends Screen {
    private final Screen parent;private final boolean wing;private UUID selected,anchor;private final Set<UUID> multi=new LinkedHashSet<>();private String group="",message="Ctrl-click: add/remove · Shift-click: range · Click eye/lock: toggle";
    public LoomLayerManagerScreen(Screen parent,boolean wing,UUID selected){super(Component.literal("Layer manager"));this.parent=parent;this.wing=wing;this.selected=selected;if(selected!=null)multi.add(selected);anchor=selected;}
    private LoomCanvas canvas(){return wing?ClientProjectWorkspace.project().elytra():ClientProjectWorkspace.project().cape();}
    private LibraryOrganization org(){return new LibraryOrganization(LoomPreferences.get());}
    private LoomCanvas shown(){var c=canvas();if(group.isEmpty())return c;return new LoomCanvas(c.width(),c.height(),c.layers().stream().filter(l->org().group(ClientProjectWorkspace.project().projectId(),l.id()).equals(group)).toList());}
    @Override protected void init(){int top=LoomScreenChrome.headerHeight(LoomUiTheme.compact(width,height))+10,right=width-172;multi.retainAll(canvas().layers().stream().map(LoomLayer::id).toList());if(canvas().layers().stream().noneMatch(l->l.id().equals(selected)))selected=canvas().layers().getLast().id();
        addRenderableWidget(new LoomButton(8,top,64,20,Component.literal("Back"),this::onClose));
        addRenderableWidget(new LoomButton(76,top,right-80,20,Component.literal(group.isEmpty()?"All groups":group),()->{List<String> groups=new ArrayList<>();groups.add("");canvas().layers().stream().map(l->org().group(ClientProjectWorkspace.project().projectId(),l.id())).filter(s->!s.isEmpty()).distinct().sorted().forEach(groups::add);group=groups.get((groups.indexOf(group)+1)%groups.size());rebuildWidgets();}));
        addRenderableWidget(new LoomLayerListWidget(8,top+25,right-8,height-top-53,this::shown,()->multi.contains(selected)?selected:null,id->{selected=id;},id->{var layer=canvas().layers().stream().filter(l->l.id().equals(id)).findFirst().orElseThrow();ClientProjectWorkspace.apply(p->LayerBatch.apply(p,wing,Set.of(id),layer.visible()?LayerBatch.Action.HIDE:LayerBatch.Action.SHOW));},id->{var layer=canvas().layers().stream().filter(l->l.id().equals(id)).findFirst().orElseThrow();ClientProjectWorkspace.apply(p->LayerBatch.apply(p,wing,Set.of(id),layer.locked()?LayerBatch.Action.UNLOCK:LayerBatch.Action.LOCK));}).setElytraThumbnails(wing).setGroupLabels(id->org().group(ClientProjectWorkspace.project().projectId(),id)).setMultiSelection(multi,(id,e)->{var list=shown().layers();if(e.hasShiftDown()&&anchor!=null){int a=0,b=0;for(int i=0;i<list.size();i++){if(list.get(i).id().equals(anchor))a=i;if(list.get(i).id().equals(id))b=i;}for(int i=Math.min(a,b);i<=Math.max(a,b);i++)multi.add(list.get(i).id());}else if(e.hasControlDown()){if(!multi.add(id))multi.remove(id);}else{multi.clear();multi.add(id);anchor=id;}selected=id;}));
        String[] labels={"Select all shown","Assign group…","Clear group","Show / hide","Lock / unlock","Duplicate","Move up","Move down","Delete selected"};
        for(int i=0;i<labels.length;i++){final int action=i;addRenderableWidget(new LoomButton(right+8,top+i*24,156,21,Component.literal(labels[i]),()->act(action)).setDanger(i==8));}
    }
    private void act(int action){try{if(action==0){shown().layers().forEach(l->multi.add(l.id()));return;}if(multi.isEmpty()){message="Select at least one layer";return;}if(action==1){minecraft.setScreen(new LoomRenameScreen(this,"Layer group","Group name","Assign group","",name->org().group(ClientProjectWorkspace.project().projectId(),multi,name)));return;}if(action==2){org().group(ClientProjectWorkspace.project().projectId(),multi,"");message="Group cleared";rebuildWidgets();return;}boolean allVisible=canvas().layers().stream().filter(l->multi.contains(l.id())).allMatch(LoomLayer::visible),allLocked=canvas().layers().stream().filter(l->multi.contains(l.id())).allMatch(LoomLayer::locked);LayerBatch.Action a=switch(action){case 3->allVisible?LayerBatch.Action.HIDE:LayerBatch.Action.SHOW;case 4->allLocked?LayerBatch.Action.UNLOCK:LayerBatch.Action.LOCK;case 5->LayerBatch.Action.DUPLICATE;case 6->LayerBatch.Action.UP;case 7->LayerBatch.Action.DOWN;default->LayerBatch.Action.DELETE;};if(action==8){var ids=Set.copyOf(multi);minecraft.setScreen(new LoomDecisionScreen(this,"Delete selected layers?",ids.size()+" layers · Ctrl+Z can undo",List.of(new LoomDecisionScreen.Choice("Delete layers",()->{ClientProjectWorkspace.apply(p->LayerBatch.apply(p,wing,ids,a));message="Layers deleted · Ctrl+Z to undo";minecraft.setScreen(this);},true))));}else{ClientProjectWorkspace.apply(p->LayerBatch.apply(p,wing,Set.copyOf(multi),a));message="Applied to "+multi.size()+" layers · Ctrl+Z to undo";rebuildWidgets();}}catch(java.io.IOException|IllegalArgumentException|IllegalStateException e){message=e.getMessage();}}
    @Override public boolean keyPressed(KeyEvent e){if(e.hasControlDownWithQuirk()&&e.key()==90){ClientProjectWorkspace.undo();rebuildWidgets();return true;}if(e.hasControlDownWithQuirk()&&e.key()==89){ClientProjectWorkspace.redo();rebuildWidgets();return true;}return super.keyPressed(e);}
    @Override public void render(GuiGraphics g,int mx,int my,float dt){LoomScreenChrome.renderBackdrop(g,width,height);LoomScreenChrome.renderBrandHeader(g,width,(wing?"Elytra":"Cape")+" layers · "+multi.size()+" selected",LoomUiTheme.compact(width,height));super.render(g,mx,my,dt);LoomScreenChrome.footer(g,width,height,font.plainSubstrByWidth(message,width-160),group.isEmpty()?"All groups":group);}
    @Override public void onClose(){minecraft.setScreen(parent);}
}
